### ISSUE TITLE
Práctica Reconocimiento de patron Hiro

### ISSUE THREAD

**Issue by Edwin-1012** [SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo_cafe-huerto-el-mamey#1]
[Practica de realidad aumentada con objetos 3d en heroku_Edwin, Alexis, Iván, Taoli.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-marcador-hiro-equipo_cafe-huerto-el-mamey/files/8605497/Practica.de.realidad.aumentada.con.objetos.3d.en.heroku_Edwin.Alexis.Ivan.Taoli.pdf)

**Comment by claudiasilvavenda** [comment]
La calif. 20%

El trabajo bien documentado.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
